[project]
name = "crewai-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.121.1",
    "crewai-tools>=0.46.0",
]
